src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Positive;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Constraints\Regex;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    #[NotBlank(
        message: 'Le nom ne peut pas être vide.'
    )]
    #[Length(
        min: 3, max: 255, minMessage: 'Le nom est trop court, 3 caractères minimum', maxMessage: 'Le nom est trop long, 255 caractères maximum'
    )]
    #[Regex(
        pattern: '/^[A-Za-z0-9\sÀ-ÿ]+$/',
        message: 'Le nom ne peut contenir que des lettres, des chiffres et des espaces.'
    )]
    private ?string $name = null;

    #[ORM\Column(length: 50, unique: true, nullable: true)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Image::class, cascade: ['persist', 'remove'])]
    private Collection $images;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $short_description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    #[NotNull]
    #[Positive]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $brand = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductVariant::class, orphanRemoval: true)]
    private Collection $productVariants;

    #[ORM\Column(nullable: true)]
    #[Range(notInRangeMessage: 'La note doit être comprise entre 0 et 5.', invalidMessage: 'Entrez un nombre', min: 0, max: 5)]
    private ?float $rating = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Discount $discount = null;

    #[ORM\Column(length: 13, nullable: true)]
    private ?string $EAN = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $added = null;

    #[ORM\ManyToMany(targetEntity: Feature::class, inversedBy: 'products', fetch: 'EAGER')]
    private Collection $features;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $feature1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $feature2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $feature3 = null;

    #[ORM\Column(nullable: true)]
    private ?bool $simpleProduct = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->productVariants = new ArrayCollection();
        $this->features = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    /**
     * @return Collection<int, ProductVariant>
     */
    public function getProductVariants(): Collection
    {
        return $this->productVariants;
    }

    public function addProductVariant(ProductVariant $productVariant): self
    {
        if (!$this->productVariants->contains($productVariant)) {
            $this->productVariants->add($productVariant);
            $productVariant->setProduct($this);
        }

        return $this;
    }

    public function removeProductVariant(ProductVariant $productVariant): self
    {
        if ($this->productVariants->removeElement($productVariant)) {
            // set the owning side to null (unless already changed)
            if ($productVariant->getProduct() === $this) {
                $productVariant->setProduct(null);
            }
        }

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDiscount(): ?Discount
    {
        return $this->discount;
    }

    public function setDiscount(?Discount $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getEAN(): ?string
    {
        return $this->EAN;
    }

    public function setEAN(string $EAN): self
    {
        $this->EAN = $EAN;

        return $this;
    }

    public function getAdded(): ?\DateTimeImmutable
    {
        return $this->added;
    }

    public function setAdded(\DateTimeImmutable $added): self
    {
        $this->added = $added;

        return $this;
    }

    /**
     * @return Collection<int, Feature>
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features->add($feature);
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        $this->features->removeElement($feature);

        return $this;
    }

    public function getFeature1(): ?string
    {
        return $this->feature1;
    }

    public function setFeature1(?string $feature1): self
    {
        $this->feature1 = $feature1;

        return $this;
    }

    public function getFeature2(): ?string
    {
        return $this->feature2;
    }

    public function setFeature2(?string $feature2): self
    {
        $this->feature2 = $feature2;

        return $this;
    }

    public function getFeature3(): ?string
    {
        return $this->feature3;
    }

    public function setFeature3(?string $feature3): self
    {
        $this->feature3 = $feature3;

        return $this;
    }

    public function isSimpleProduct(): ?bool
    {
        return $this->simpleProduct;
    }

    public function setSimpleProduct(bool $simpleProduct): self
    {
        $this->simpleProduct = $simpleProduct;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Brand;
use App\Entity\Category;
use App\Entity\Discount;
use App\Entity\Feature;
use App\Entity\Product;
use App\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Count;
use Symfony\Component\Validator\Constraints\File;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom du produit',
                'attr' => [
                    'class' => 'form-control border'
                ]
            ])
            ->add('category', EntityType::class, [
                'label' => 'Catégorie',
                'class' => Category::class,
                'query_builder' => function (CategoryRepository $categoryRepository) {
                    return $categoryRepository->createQueryBuilder('c')
                        ->where('c.parent is not null')
                        ->andWhere('SIZE(c.children) = 0');
                },
                'attr' => [
                    'class' => 'form-control border'
                ]
            ])
            ->add('brand', EntityType::class, [
                'label' => 'Marque',
                'class' => Brand::class,
                'attr' => [
                    'class' => 'form-select'
                ]
            ])
            ->add('images', FileType::class, [
                'label' => 'Images',
                'required' => false,
                'mapped' => false,
                'multiple' => true,
                'constraints' => [
                    new Count([
                        'max' => 8,
                        'maxMessage' => 'Vous ne pouvez pas ajouter plus de 8 images'
                    ]),
                    new All([
                        new File([
                            'maxSize' => '5M',
                            'maxSizeMessage' => 'Le fichier est trop volumineux, 5MB maximum.',
                            'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'webp'],
                            'extensionsMessage' => 'Le fichier n\'est pas au bon format, jpg, jpeg, png, gif et webp uniquement.'
                        ])
                    ])
                ],
                'attr' => [
                    'class' => 'form-control border'
                ]
            ])
            ->add('features', EntityType::class, [
                'class' => Feature::class,
                'label' => 'Caractéristiques',
                'expanded' => true,
                'multiple' => true,
                'required' => false,
                'attr' => [
                    'class' => 'form-select'
                ],
                'choice_attr' => function($choice, $key, $value) {
                    return [
                        'class' => 'ms-3'
                    ];
                }
            ])
            ->add('feature1', TextType::class, [
                'label' => 'Première caractéristique propre',
                'attr' => [
                    'class' => 'form-control border',
                ],
                'required' => false
            ])
            ->add('feature2', TextType::class, [
                'label' => 'Seconde caractéristique propre',
                'attr' => [
                    'class' => 'form-control border',
                ],
                'required' => false
            ])
            ->add('feature3', TextType::class, [
                'label' => 'Troisième caractéristique propre',
                'attr' => [
                    'class' => 'form-control border',
                ],
                'required' => false
            ])
            ->add('short_description', TextareaType::class, [
                'label' => 'Description courte',
                'attr' => [
                    'class' => 'form-control border',
                    'rows' => 2
                ],
                'required' => false
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
                'attr' => [
                    'class' => 'form-control border',
                    'rows' => 5
                ],
                'required' => false
            ])
            ->add('price', NumberType::class, [
                'label' => 'Prix',
                'attr' => [
                    'class' => 'form-control border'
                ]
            ])
            ->add('rating', NumberType::class, [
                'label' => 'Note',
                'attr' => [
                    'class' => 'form-control border'
                ],
                'required' => false
            ])
            ->add('discount', EntityType::class, [
                'label' => 'Réduction',
                'class' => Discount::class,
                'attr' => [
                    'class' => 'form-select'
                ],
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}

    {{ form_label(form.name) }}
    {{ form_widget(form.name) }}

    {{ form_label(form.category) }}
    {{ form_widget(form.category) }}

    {{ form_label(form.brand) }}
    {{ form_widget(form.brand) }}

    {{ form_label(form.images) }}
    {{ form_widget(form.images) }}

    {{ form_label(form.features) }}
    {{ form_widget(form.features) }}

    {{ form_label(form.feature1) }}
    {{ form_widget(form.feature1) }}

    {{ form_label(form.feature2) }}
    {{ form_widget(form.feature2) }}

    {{ form_label(form.feature3) }}
    {{ form_widget(form.feature3) }}

    {{ form_label(form.short_description) }}
    {{ form_widget(form.short_description) }}

    {{ form_label(form.description) }}
    {{ form_widget(form.description) }}

    {{ form_label(form.price) }}
    {{ form_widget(form.price) }}

    {{ form_label(form.rating) }}
    {{ form_widget(form.rating) }}

    {{ form_label(form.discount) }}
    {{ form_widget(form.discount) }}

    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Modifier un produit{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Modifier un produit</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_product_index') }}">Retour à la liste</a>
    </div>
    <div class="row py-3">
        <div class="product-images d-flex flex-wrap gap-3">
            {% set images = product.images %}
            {% if images|length > 0 %}
                {% for image in images %}
                    <div class="crud-thumbnail-div position-relative"
                         data-controller="admin-product-remove-image"
                         data-product-id="{{ product.id }}"
                         data-image-id="{{ image.id }}">
                        <img
                                class="img-fluid"
                                src="{{ asset('images/' ~ image.path) }}"
                                alt="{{ image.alt }}">
                        <img
                                class="position-absolute top-0 end-0"
                                src="{{ asset('images/icons/remove.png') }}"
                                alt="remove icon"
                                data-admin-product-remove-image-target="removeIcon">
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row py-3 border-bottom">
        {{ include('product/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    </div>
{% endblock %}

templates/product/index.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Produits</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_product_new') }}">Ajouter un nouveau produit</a>
    </div>
    <div class="row py-3">
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th class="d-none d-md-table-cell">Catégorie</th>
                <th>Marque</th>
                <th>Images</th>
                <th class="d-none d-md-table-cell">Description courte</th>
                <th>Prix</th>
                <th class="d-none d-md-table-cell">Note</th>
                <th class="d-none d-md-table-cell">EAN</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                {% if product.productVariants|length == 0 %}
                <td style="background-color: rgba(255, 0, 0, 0.5);">
                    {{ product.name }}</td>
                {% elseif product.isInStock %}
                    <td style="background-color: rgba(0, 128, 0, 0.5);">
                        {{ product.name }}</td>
                {% else %}
                    <td style="background-color: rgba(255, 255, 0, 0.5);">
                        {{ product.name }}</td>
                {% endif %}
                <td class="d-none d-md-table-cell">{{ product.category.name }}</td>
                <td>{{ product.brand.name }}</td>
                <td>
                    {% set images = product.images %}
                    {% if images|length > 0 %}
                        <img
                                class="crud-thumbnail"
                                src="{{ asset('images/' ~ images[0].path) }}"
                                alt="{{ images[0].alt }}">
                    {% endif %}
                </td>
                <td class="d-none d-md-table-cell">{{ product.shortDescription ? product.shortDescription|slice(0, 100) ~ '...' : '' }}</td>
                <td>{{ product.price | number_format(2, '.', ',') | format_currency('EUR', locale='fr') }}</td>
                <td class="d-none d-md-table-cell">{{ product.rating ? product.rating ~ '/5' : 'pas de note' }}</td>
                <td class="d-none d-md-table-cell">{{ product.EAN }}</td>
                <td class="d-flex flex-column justify-content-center">
                    <div class="d-flex gap-1">
                        <a class="btn btn-info" href="{{ path('app_product_show', {'id': product.id}) }}">Voir</a>
                        <a class="btn btn-warning" href="{{ path('app_product_edit', {'id': product.id}) }}">Modifier</a>
                    </div>
                    {{ include('product/_delete_form.html.twig') }}
                    <a class="btn btn-primary" href="{{ path('app_product_variants', {'id': product.id}) }}">Variants</a>
                </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="17">Aucun produit trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/product/new.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Ajouter un produit</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_product_index') }}">Retour à la liste</a>
    </div>
    <div class="row py-3">
        {{ include('product/_form.html.twig') }}
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>{{ product.name }}</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_product_index') }}">Retour à la liste</a>
        <a href="{{ path('app_product_edit', {'id': product.id}) }}">Modifier</a>
    </div>
    <div class="row py-3">
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ product.name }}</td>
            </tr>
            <tr>
                <th>Catégorie</th>
                <td>{{ product.category.name }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ product.brand.name }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>
                    {% set images = product.images %}
                    {% if images|length > 0 %}
                        {% for image in images %}
                            <img
                                    class="crud-thumbnail"
                                    src="{{ asset('images/' ~ image.path) }}"
                                    alt="{{ image.alt }}">
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Caractéristiques</th>
                <td class="d-flex gap-3">
                    {% for feature in product.features %}
                        <div class="d-flex flex-column text-center">
                            <img class="mx-auto"
                                    src="{{ asset('images/' ~ feature.image.path) }}"
                                    alt="{{ feature.image.alt }}"
                                    style="width: 40px; height: 40px;">
                            <div>{{ feature.name }}</div>
                        </div>
                    {% endfor %}
                </td>
{#                <td>{{ product.features }}</td>#}
            </tr>
            <tr>
                <th>Caractéristiques personnalisées</th>
                <td>{% if product.feature1 %}
                        {{ product.feature1 }}
                    {% endif %}
                    {% if product.feature2 %}
                        {{ ', ' ~ product.feature2 }}
                    {% endif %}
                    {% if product.feature3 %}
                        {{ ', ' ~ product.feature3 }}
                    {% endif %}</td>
            </tr>
            <tr>
                <th>Description courte</th>
                <td>{{ product.shortDescription }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ product.price ~ '€' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ product.rating ? product.rating ~ '/5' : '' }}</td>
            </tr>
            <tr>
                <th>Ajouté le</th>
                <td>{{ product.added.format('d-m-Y')|format }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ product.slug }}</td>
            </tr>
            <tr>
                <th>EAN</th>
                <td>{{ product.EAN }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/product/variants.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Variants{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Variants de {{ product.name }}</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_product_index') }}">Retour à la liste</a>
    </div>
    <div class="row py-3">
        <table class="table">
            <thead>
            <tr>
                <th class="d-none d-md-table-cell">Id</th>
                <th>Code</th>
                <th>Impact sur le prix</th>
                <th>Prix Total</th>
                <th>Quantité</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for productVariant in product.productVariants %}
                <tr>
                    <td class="d-none d-md-table-cell">{{ productVariant.id }}</td>
                    <td>{{ productVariant.code }}</td>
                    <td>
                        {% if not product.simpleProduct %}
                        <input
                                type="text"
                                name="admin-variant-price"
                                data-controller="admin-product-variant-price"
                                data-variant-id="{{ productVariant.id }}"
                                value="{{ productVariant.price ? productVariant.price : '' }}"
                                style="width: 50px;">€
                        {% endif %}
                    </td>
                    <td>
                        <div name="admin-total-price" data-base-price="{{ product.price }}">
                            {{ productVariant.price ?
                            ((productVariant.price + product.price) | number_format(2, '.', ',') | format_currency('EUR', locale='fr') ) :
                            (product.price | number_format(2, '.', ',') | format_currency('EUR', locale='fr') ) }}
                        </div>
                    </td>
                    <td>
                        <input
                                type="number"
                                name="admin-stock"
                                data-controller="admin-product-variant-stock"
                                data-variant-id="{{ productVariant.id }}"
                                value="{{ productVariant.stock }}"
                                min="0"
                                style="width: 50px;">
                    </td>
                    <td>
                        <form method="post" action="{{ path('app_product_delete_variant', {'id': product.id, 'variantId': productVariant.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ productVariant.getId()) }}">
                            <button class="btn">Supprimer</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row" data-controller="admin-product-variant-options">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Ajouter / Réinitialiser les variants') }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}