src/Entity/Hero.php
<?php

namespace App\Entity;

use App\Repository\HeroRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Url;

#[ORM\Entity(repositoryClass: HeroRepository::class)]
class Hero
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Regex(pattern: '/^[^<>;=#{}()*+]/u', message: 'Le message ne peut contenir que des chiffres, des lettres et . , ! ? \'')]
    private ?string $message = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Regex(pattern: '/^[^<>;=]*$/', message: 'Le message ne peut contenir que des chiffres, des lettres et ".", ",", "!", "?", "\'"')]
    #[Length(min: 3, max: 50, minMessage: 'Le message du bouton doit contenir au moins 3 caractères.', maxMessage: 'Le message du bouton doit contenir au maximum 50 caractères.')]
    private ?string $button_message = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Url(message: 'Le lien doit être une URL valide.')]
    private ?string $link = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Image $image = null;

    #[ORM\Column]
    private ?bool $active = null;

    public function __construct()
    {
        $this->active = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getButtonMessage(): ?string
    {
        return $this->button_message;
    }

    public function setButtonMessage(?string $button_message): self
    {
        $this->button_message = $button_message;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

templates/components/_categoriesTree.html.twig
<div class="category-tree row d-flex ms-1 mb-3">

    {% for category in tree %}
    <div class="col-auto px-0">
        <a class="arrow-button" href="{{ path('show_category', {'slug': category.slug}) }}">
            {{ category.name }}
{#                <button class="arrow-button">{{ category.name }}</button>#}
        </a>
    </div>
    {% endfor %}

        <div class="col-auto px-0">
            <a class="arrow-button" href="{{ path('show_category', {'slug': category.slug}) }}">
                {{ category.name }}
{#                        <button class="arrow-button">{{ category.name }}</button>#}
            </a>
        </div>
</div>

templates/components/_flashmessages.html.twig
<div class="row" id = "flash-messages">
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            {% if label == 'success' %}
                <div class="alert alert-success">
            {% elseif label == 'error'%}
                <div class="alert alert-danger">
            {% else %}
                <div class="alert alert-info">
            {% endif %}
                    {{ message }}
                </div>
        {% endfor %}
    {% endfor %}
</div>

templates/components/_footer.html.twig
<footer class="footer container-fluid bg-fd2048 text-white px-3 py-4 ps-md-5">
    <div class="row">
        <p>
            Des questions, Appelez le (+33) 6 69 69 69 69
        </p>
    </div>
    <div class="row d-flex justify-content-between mb-3">
        <div class="col-10 col-md-3 mx-auto">
            <h5 class="mb-3">Service client</h5>
            <ul class="list-unstyled d-block">
                <li><a href="{{ path('app_delivery') }}">Livraison et discrétion</a></li>
                <li><a href="{{ path('app_return') }}">Retours</a></li>
                <li><a href="{{ path('app_payments') }}">Modes de paiement</a></li>
            </ul>
        </div>

        <div class="col-10 col-md-3 mx-auto">
            <h5 class="mb-3">A propos</h5>
            <ul class="list-unstyled d-block">
                <li><a href="{{ path('app_contact') }}">Contact</a></li>
                <li><a href="{{ path('app_about') }}">A propos de nous</a></li>
            </ul>
        </div>

        <div class="col-10 col-md-3 mx-auto">
            <h5 class="mb-3">Fidélité</h5>
            <ul class="list-unstyled d-block">
                <li><a href="{{ path('app_gift') }}">Cartes cadeaux</a></li>
                <li><a href="{{ path('app_profile') }}">Mon compte</a></li>
            </ul>
        </div>

        <div class="col-10 col-md-3 mx-auto">
            <h5 class="mb-3">Informations</h5>
            <ul class="list-unstyled d-block">
                <li><a href="{{ path('app_cgu') }}">Conditions générales</a></li>
                <li><a href="{{ path('app_rgpd') }}">Mentions légales</a></li>
                <li><a href="{{ path('app_faq') }}">FAQ</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-10 col-md-3 me-auto">
            <img
                    class="logo-image"
                    src="{{ asset('images/logo_white.png') }}"
                    alt="Logo Header"
                    style="max-height: 60px;">
            <p>
                FeuOCul France
            </p>
        </div>
    </div>
</footer>

templates/components/_hero.html.twig
{% if hero and hero is not null %}
    <div class="hero">
        {% include 'components/_navbar.html.twig' %}
        <img
                class="hero-background img-fluid"
                alt="{{ 'bannière du site ' ~ image.alt }}"
                src="{{ asset('images/' ~ hero.image.path) }}">
        <div class="hero-container">

{#            Message d'erreur en cas de redirection si un malotru essaye d'accéder à l'admin#}
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-danger text-center">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}

            {% if hero.message is defined and hero.message is not null %}
                <h1 class="hero-container_title text-md-xl text-sm-l">{{ hero.message }}</h1>
            {% endif %}
            {% if hero.link is defined and hero.link is not null %}
                <a class="btn-fd2048 text-center d-inline-block rounded-pill fw-bold text-white p-2 mx-auto"
                    href="{{ hero.link }}">
                    {% if hero.buttonMessage %}
                        {{ hero.buttonMessage }}
                    {% else %}
                        En savoir plus
                    {% endif %}
                </a>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/components/_infos.html.twig
<div class="infos container-fluid bg-fd2048 py-4">
    <div class="row justify-content-center">
        <div class="col-lg-2 col-md-4 col-sm-6 d-flex flex-column text-center">
            <img class="infos-image mx-auto" src="{{ asset('images/icons/startup.png') }}" alt="icône fusée">
            <h2 class="fw-bold fs-5 text-dark">Livraison rapide</h2>
            <p class="fs-6 text-dark">Colissimo, Chronopost 24h, Mondial relay, Click & Collect</p>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6 d-flex flex-column text-center">
            <img class="infos-image mx-auto" src="{{ asset('images/icons/carnival-mask-silhouette.png') }}" alt="icône incognito">
            <h2 class="fw-bold fs-5 text-dark">Discretion assurée</h2>
            <p class="fs-6 text-dark">Colis sans mention</p>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6 d-flex flex-column text-center">
            <img class="infos-image mx-auto" src="{{ asset('images/icons/credit-card.png') }}" alt="icône paiement">
            <h2 class="fw-bold fs-5 text-dark">Paiement en 3x sans frais</h2>
            <p class="fs-6 text-dark">Dès 150 euros d'achat</p>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6 d-flex flex-column text-center">
            <img class="infos-image mx-auto" src="{{ asset('images/icons/money.png') }}" alt="icône satisfait remboursé">
            <h2 class="fw-bold fs-5 text-dark">Satisfait ou remboursé</h2>
            <p class="fs-6 text-dark">15 jours pour se rétracter</p>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6 d-flex flex-column text-center">
            <img class="infos-image mx-auto" src="{{ asset('images/icons/free-delivery.png') }}" alt="icône livraison">
            <h2 class="fw-bold fs-5 text-dark">Livraison offerte</h2>
            <p class="fs-6 text-dark">Dès 100 euros d'achat</p>
        </div>
    </div>
</div>

templates/components/_navbar.html.twig
<nav class="navbar navbar-expand-md" id="nav">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link"
                       href="#"
                       data-action="click->toggle-sidebar-categories#toggle">
                        <i class="bi bi-list fa-lg me-3 fw-bolder"></i>Tous les produits
                    </a>
                </li>
            {% for category in categories %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('show_category',
                        {'slug': category.slug}) }}">{{ category.name }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</nav>

templates/components/_sidebarcategories.html.twig
<div id="sidebar-wrap" class="d-none">
    <div class="sidebar-categories col-12 col-md-4 text-black position-absolute bg-white min-vh-100"
        style="z-index: 999;">
        <div class="d-flex justify-content-between align-items-center bg-dark p-3">
            <a class="mb-2" href="{{ path('app_home') }}">
                <img class="logo-image img-fluid"
                    src="{{ asset('images/logo.png') }}"
                    alt="Logo Header"
                    style="max-width: 120px;">
            </a>
            <i class="bi bi-x me-3 fa-lg text-white" data-action="click->toggle-sidebar-categories#toggle"></i>
        </div>
        <ul class="d-block list-unstyled bg-white px-3">
            {% if app.user %}
                <li>
                    <a href="{{ path('app_profile') }}" class="text-decoration-none d-flex justify-content-between border-bottom align-items-center my-auto px-3">
                        <div class="d-block d-md-none sidebar-login d-flex gap-3 align-items-center my-3">
                            <img src="{{ asset('images/icons/user-pink.png') }}"
                                 alt="icône profil"
                                 style="max-height: 50px">
                            <h3 class="category-header text-f46a79 fw-bold">Mon compte</h3>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="{{ path('app_logout') }}" class="text-decoration-none d-flex justify-content-between border-bottom align-items-center my-auto px-3">
                        <div class="d-block d-md-none sidebar-login d-flex gap-3 align-items-center my-3">
                            <img src="{{ asset('images/icons/logout-pink.png') }}"
                                 alt="icône déconnexion"
                                 style="max-height: 50px">
                            <h3 class="category-header text-f46a79 fw-bold">Déconnexion</h3>
                        </div>
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{{ path('app_login') }}" class="text-decoration-none d-flex justify-content-between border-bottom align-items-center my-auto px-3">
                        <div class="d-block d-md-none sidebar-login d-flex gap-3 align-items-center my-3">
                            <img src="{{ asset('images/icons/login-pink.png') }}"
                                 alt="icône connexion"
                                 style="max-height: 50px">
                            <h3 class="category-header text-f46a79 fw-bold">Connexion</h3>
                        </div>
                    </a>
                </li>
            {% endif %}
            <li>
                <a href="{{ path('app_cart') }}" class="text-decoration-none d-flex justify-content-between border-bottom align-items-center my-auto px-3">
                    <div class="d-block d-md-none sidebar-login d-flex gap-3 align-items-center my-3">
                        <img src="{{ asset('images/icons/cart-pink.png') }}"
                             alt="icône panier"
                             style="max-height: 50px">
                        <h3 class="category-header text-f46a79 fw-bold">Panier</h3>
                    </div>
                </a>
            </li>
            {% for category in categories %}
                <li>
                    <div class="main-category d-flex justify-content-between border-bottom align-items-center my-auto px-3"
                         data-target="{{ 'subcategory' ~ category.name }}">
                        <div class="d-flex gap-3 align-items-center my-3">
                            <img src="{{ asset('images/' ~ category.image.path) }}"
                                alt="{{ category.image.alt }}"
                                style="max-height: 50px">
                            <h3 class="category-header text-f46a79 fw-bold">{{ category.name }}</h3>
                        </div>
                        <i class="bi bi-caret-right align-self-center text-fd2048"></i>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="sidebar-overlay"
         class="position-fixed top-0 start-0 w-100 h-100 bg-white opacity-50"
         data-action="click->toggle-sidebar-categories#toggle click->toggle-sidebar-categories#hide"
         style="z-index: 1;">
    </div>
</div>

{% for category in categories %}
    <div id ="{{ 'subcategory' ~ category.name }}"
         class="child-category col-12 col-md-4 text-black position-absolute bg-white min-vh-100 d-none px-3"
         data-controller="toggle-subcategory"
         style="z-index: 999;">
        <div class="d-flex align-items-center my-3 gap-3 border-bottom"
             data-action="click->toggle-subcategory#toggle">
            <i class="bi bi-caret-left align-self-center text-fd2048"></i>
            <div class="d-flex gap-3 align-items-center my-3">
                <h2 class="text-f46a79 category-header">{{ category.name }}</h2>
                <img src="{{ asset('images/' ~ category.image.path) }}"
                     alt="{{ category.image.alt }}"
                     style="max-height: 50px">
            </div>
        </div>
        {% for cat in category.children %}
            <h3 class="text-f46a79">{{ cat.name }}</h3>
            {% for subcat in cat.children %}
                <a class="text-reset text-decoration-none" href="{{ path('show_category', {'slug': subcat.slug}) }}">
                    <p class="category-link" style="margin-left: 10px;">{{ subcat.name }}</p>
                </a>
            {% endfor %}
        {% endfor %}
    </div>
{% endfor %}

templates/components/_starcomponent.html.twig
{% for i in 1..5 %}
    {% if i <= note %}
        <i class="bi bi-star-fill"></i>
    {% elseif i - 0.5 <= note %}
        <i class="bi bi-star-half"></i>
    {% else %}
        <i class="bi bi-star"></i>
    {% endif %}
{% endfor %}

templates/components/_textband.html.twig
<div class="shadow-sm" style="background-color: {{ background }}; color: {{ color }};">
    <div class="container h-30 d-flex align-items-center justify-content-center small fw-bold">
        {{ text }}
    </div>
</div>