src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte avec cet email existe déjà.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[NotBlank(message: 'Veuillez saisir un adresse email.')]
    #[Length(
        min: 6, max: 180, minMessage: 'Le mail est trop court, 6 caractères minimum', maxMessage: 'Le mail est trop long, 180 caractères maximum'
    )]
    #[Email(
        message: 'L\'adresse email {{ value }} n\'est pas valide.'
    )]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[NotBlank(
        message: 'Le mot de passe ne peut pas être vide.', allowNull: true
    )]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    #[NotBlank(
        message: 'T\'as pas de prénom ?'
    )]
    #[Length(
        min: 2, max: 50, minMessage: 'Ton prénom c\'est lettre ? Sérieux ?', maxMessage: 'C\'est pas un prénom ça, c\'est trop long, 50 caractères max'
    )]
    #[Regex(
        pattern: '/^[\p{L}\-]+(?!-)$/',
        message: 'Dans un prénom il n\'y a que des lettres et des fois un tiret pour séparer 2 lettres ...'
    )]
    private ?string $first_name = null;

    #[ORM\Column(length: 50)]
    #[NotBlank(
        message: 'T\'as pas de nom ?'
    )]
    #[Length(
        min: 2, max: 50, minMessage: 'Ton nom c\'est lettre ? Sérieux ?', maxMessage: 'C\'est pas un nom ça, c\'est un roman, 50 caractères max'
    )]
    #[Regex(
        pattern: '/^[\p{L}\-]+(?!-)$/',
        message: 'Dans un nom il n\'y a que des lettres et des fois un tiret pour séparer 2 lettres ...'
    )]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[NotBlank(
        message: 'T\'habites nulle part ? Ton adresse est vide', allowNull: true
    )]
    #[Length(
        min: 2, max: 255, minMessage: 'L\'adresse doit contenir au moins 2 caractères', maxMessage: 'C\'est très très long ça ! 255 caractères maximum'
    )]
    #[Regex(
        pattern: '/^[\p{L}\d\s\/\'-]*[a-zA-Z][\p{L}\d\s\/\'-]*$/u',
        message: 'Une adresse ne peut contenir que des lettres, des chiffres, des tirets ou des slash.'
    )]
    private ?string $address = null;

    #[ORM\Column(length: 5, nullable: true)]
    #[NotBlank(
        message: 'Ton code postal est vide', allowNull: true
    )]
    #[Length(
        min: 5, max: 5, exactMessage: 'Un code postal c\'est 5 caractères doudou !'
    )]
    #[Regex(
        pattern: '/^[a-zA-Z0-9]+$/', message: 'Il faut seulement des chiffres et des lettres dans ton code postal.'
    )]
    private ?string $zipcode = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[NotBlank(
        message: 'Ta ville est vide', allowNull: true
    )]
    #[Length(
        min: 1, max: 45, minMessage: 'Le village avec le nom de plus court de France c\'est Y, et y a au moins une lettre dedans !',
        maxMessage: 'C\'est trop long, la commune française au nom le plus long en comporte 45 !'
    )]
    #[Regex(
        pattern: '/^[\p{L}\s\'-]+$/u',
        message: 'Pour la ville, j\'accepte seulement des lettres, des espaces, des apostrophes et des tirets'
    )]
    private ?string $city = null;

    #[ORM\Column(length: 10, nullable: true)]
    #[NotBlank(
        message: 'Un numéro de téléphone sans numéros ? Ah ben mon cochon !', allowNull: true
    )]
    #[Length(
        min: 10, max: 10, exactMessage: 'Il manque des numéros chouchou, il en faut 10 pour ton téléphone !'
    )]
    #[Regex(
        pattern: '/^[0-9]+$/',
        message: 'Il faut seulement mettre des numéros dans ton numéro de téléphone sinon je ne pourrai pas t\'appeler !'
    )]
    private ?string $phone = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isValidated = false;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist'])]
    private ?Cart $cart = null;

    #[ORM\Column(length: 32)]
    private ?string $validationKey = null;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->validationKey = md5(microtime(TRUE) * 100000);
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name ?? '';

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name ?? '';

        return $this;
    }

    public function getBirth(): ?\DateTimeInterface
    {
        return $this->birth;
    }

    public function setBirth(?\DateTimeInterface $birth): self
    {
        $this->birth = $birth;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = empty($address) ? null : $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(?string $zipcode): self
    {
        $this->zipcode = empty($zipcode) ? null : $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = empty($city) ? null : $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = empty($phone) ? null : $phone;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        // unset the owning side of the relation if necessary
        if ($cart === null && $this->cart !== null) {
            $this->cart->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($cart !== null && $cart->getUser() !== $this) {
            $cart->setUser($this);
        }

        $this->cart = $cart;

        return $this;
    }

    public function getValidationKey(): ?string
    {
        return $this->validationKey;
    }

    public function setValidationKey(string $validationKey): self
    {
        $this->validationKey = $validationKey;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Adresse email valide'
            ])
            ->add('password', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Mot de passe',
                'mapped' => false
            ])
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Administrateur' => 'ROLE_ADMIN',
                    'Utilisateur' => 'ROLE_USER'
                ],
                'expanded' => true,
                'multiple' => true,
                'attr' => [
                    'class' => 'form-check'
                ]
            ])
            ->add('first_name', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Prénom',
                'required' => true
            ])
            ->add('last_name', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Nom',
                'required' => true
            ])
            ->add('birth', DateType::class, [
                'attr' => [
                    'class' => 'form-control border-0'
                ],
                'label' => 'Date de naissance',
                'required' => true,
                'years' => range(date('Y') - 100, date('Y')),
                'constraints' => [
                    new LessThanOrEqual([
                        'value' => 'today',
                        'message' => 'Vous devez choisir une date antérieure et qui correspond à un utilisateur majeur.'
                    ])
                ]
            ])
            ->add('address', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Adresse',
                'required' => false,
            ])
            ->add('zipcode', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Code postal',
                'required' => false,
            ])
            ->add('city', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Ville',
                'required' => false
            ])
            ->add('phone', TextType::class, [
                'attr' => [
                    'class' => 'form-control border'
                ],
                'label' => 'Numéro de téléphone',
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserEditType;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Service\UserService;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/admin/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        try {
            $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');
        } catch (AccessDeniedException $e) {
            $this->addFlash('error', 'Vous ne bénéficiez pas des droits pour accéder à cette page.');
            return $this->redirectToRoute('app_admin');
        }
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserService $userService): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && !$form->isValid()) {
            foreach ($form->getErrors(true) as $error) {
                $this->addFlash('error', $error->getMessage());
            }
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $form['password']->getData();
            $birth = $form['birth']->getData();
            try {
                $userService->createUser($user, $password, $birth);
            } catch (Exception $e) {
                $this->addFlash('error', $e->getMessage());
                return $this->redirectToRoute('app_user_new');
            }

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && !$form->isValid()) {
            foreach ($form->getErrors(true) as $error) {
                $this->addFlash('error', $error->getMessage());
            }
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
            $this->addFlash('success', 'Utilisateur supprimé avec succès.');
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}

    {{ form_label(form.email) }}
    {{ form_widget(form.email) }}

    {{ form_label(form.password) }}
    {{ form_widget(form.password) }}

    {{ form_label(form.roles) }}
    {{ form_widget(form.roles) }}

    {{ form_label(form.first_name) }}
    {{ form_widget(form.first_name) }}

    {{ form_label(form.last_name) }}
    {{ form_widget(form.last_name) }}

    {{ form_label(form.birth) }}
    {{ form_widget(form.birth) }}

    {{ form_label(form.address) }}
    {{ form_widget(form.address) }}

    {{ form_label(form.zipcode) }}
    {{ form_widget(form.zipcode) }}

    {{ form_label(form.city) }}
    {{ form_widget(form.city) }}

    {{ form_label(form.phone) }}
    {{ form_widget(form.phone) }}

    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Modifier un utilisateur{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Modifier un utilisateur</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_user_index') }}">Retour à la liste</a>
    </div>
    <div class="row py-3">
        {{ include('user/_form.html.twig', {'button_label': 'Modifier'}) }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Utilisateurs</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_user_new') }}">Ajouter un nouvel utilisateur</a>
    </div>
    <div class="row py-3">
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th class="d-none d-md-table-cell">Prénom</th>
                <th class="d-none d-md-table-cell">Nom</th>
                <th class="d-none d-md-table-cell">Date de naissance</th>
                <th class="d-none d-md-table-cell">Téléphone</th>
                <th class="d-none d-md-table-cell">Créé le</th>
                <th class="d-none d-md-table-cell">Validé ?</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.roles is not empty and ('ROLE_SUPER_ADMIN' in user.roles or 'ROLE_ADMIN' in user.roles) ? 'Administrateur' : 'Utilisateur' }}</td>
                    <td class="d-none d-md-table-cell">{{ user.firstName|capitalize }}</td>
                    <td class="d-none d-md-table-cell">{{ user.lastName|capitalize }}</td>
                    <td class="d-none d-md-table-cell">{{ user.birth ? user.birth|date('Y-m-d') : '' }}</td>
                    <td class="d-none d-md-table-cell">{{ user.phone }}</td>
                    <td class="d-none d-md-table-cell">{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td class="d-none d-md-table-cell">{{ user.isValidated ? 'Oui' : 'Non' }}</td>
                    <td>
                        <a href="{{ path('app_user_show', {'id': user.id}) }}">Voir</a>
                        <a href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier</a>
                        {{ include('user/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="14">Aucun utilisateur</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/user/new.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Nouvel utilisateur{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>Ajouter un nouvel utilisateur</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_user_index') }}">Retour à la liste</a>
    </div>
    <div class="row py-3">
        {{ include('user/_form.html.twig') }}
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <div class="row py-3 border-bottom">
        <h1>{{ user.email }}</h1>
    </div>
    <div class="row py-3 border-bottom">
        <a href="{{ path('app_user_index') }}">Retour à la liste</a>
        <a href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier</a>
    </div>
    <div class="row py-3">
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles is not empty and ('ROLE_SUPER_ADMIN' in user.roles or 'ROLE_ADMIN' in user.roles) ? 'Administrateur' : 'Utilisateur' }}</td>            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>{{ user.birth ? user.birth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ user.zipcode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ user.city }}</td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ user.phone }}</td>
            </tr>
            <tr>
                <th>Créé le</th>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Validé ?</th>
                <td>{{ user.isValidated ? 'Compte validé' : 'Compte non validé' }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}